version: "3.4"
services:
  morse-code-translator:
    tty: true
    image: "morse-code-translator"
    stdin_open: true
    build:
      context: .
      target: "development"
    ports:
      - "5001:5001"
    volumes:
      - ".:/app"
    command: ["python", "run.py"]
    env_file:
      - .env
    
  rabbit-mq:
    image: rabbitmq:3.9.11
    ports:
        - "5672:5672"
  
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
